In [2]:
import numpy as np

In [2]:
def squares(values):
    result = []
    for v in values:
        result.append(v * v)
    return result
to_square = range(10000)
%timeit squares(to_square)

1.42 ms ± 33.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [2]:
array_to_square = np.arange(0, 10000)
%timeit array_to_square ** 2

5.8 µs ± 120 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## numpy核心功能ndarray

ndarray的基础
* ndarray.ndim 数组轴的个数，在Python的世界中，轴的个数被称为秩；
* ndarray.shape 数组的维度；
* ndarray.size 数组中元素的个数；
* ndarray.dtype 一个用来描述数组中元素类型的对象；
* ndarray.itemsize 数组中每个元素的字节大小
* ndarray.data 包含实际数组的缓存区，我们实际不需要这个。

In [3]:
x = np.array([1, 2, 3, 4, 5])
x

array([1, 2, 3, 4, 5])

In [4]:
type(x)

numpy.ndarray

In [5]:
x.ndim

1

In [7]:
x.shape

(5,)

In [8]:
x.size

5

In [9]:
x.itemsize

8

In [10]:
x.data

In [12]:
y = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
y

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [13]:
y.ndim

2

In [14]:
y.shape

(2, 5)

In [15]:
y.size

10

In [16]:
y.itemsize

8

In [17]:
y.data

In [18]:
x1 = np.array([1, 2, 3, 4.0, 5.0])
x1.dtype, x.dtype

(dtype('float64'), dtype('int64'))

create ndarray

In [19]:
x2 = np.array([1] * 5)
x2

array([1, 1, 1, 1, 1])

In [20]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [21]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.array(range(0, 10, 2))

array([0, 2, 4, 6, 8])

In [23]:
np.array(range(10, 0, -1))

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [24]:
np.linspace(0, 10, 5)      # 线性的方式创建

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [25]:
np.linspace?

In [27]:
# 向量化操作
print(x)
print(x1)
x + x1

[1 2 3 4 5]
[ 1.  2.  3.  4.  5.]


array([  2.,   4.,   6.,   8.,  10.])

In [28]:
# 生成多维数组，进行链式调用
x2 = np.arange(0, 12).reshape(4, 3)
x2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
np.size(x2)

12

In [30]:
np.size(x2, 0)

4

In [31]:
np.size(x2, 1)

3

In [32]:
np.zeros((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [33]:
np.ones((2, 3, 4), dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [34]:
np.empty((5, 6))     # 生成的值实际上是没有意义的

array([[  0.00000000e+000,   3.10503637e+231,   2.17461181e-314,
          2.18965409e-314,   2.18965566e-314,   2.18810018e-314],
       [  2.17471935e-314,   2.17463932e-314,   2.18639059e-314,
          2.18809986e-314,   2.18639130e-314,   2.18665470e-314],
       [  0.00000000e+000,   0.00000000e+000,   2.18662445e-314,
          2.18809979e-314,   2.18972361e-314,   2.17471910e-314],
       [  2.18648432e-314,   2.18809979e-314,   2.18972361e-314,
          2.17471910e-314,   2.18648432e-314,   2.18665317e-314],
       [  2.19022719e-314,   2.18632178e-314,   2.18665395e-314,
          2.18965438e-314,  -1.28822983e-231,   2.08600688e-308]])

In [35]:
np.random.randint(0, 10, 3)    #生成随机整数

array([9, 0, 4])

In [36]:
np.random.random(10)      # 生成随机数

array([ 0.18120502,  0.84757688,  0.05432345,  0.43468528,  0.73470585,
        0.62599592,  0.73159521,  0.71922365,  0.90469856,  0.81241894])

## 选择数组中的元素

In [37]:
x

array([1, 2, 3, 4, 5])

In [38]:
x[0], x[3]

(1, 4)

In [39]:
y

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [40]:
y[1, 3]

9

In [41]:
y[0,]

array([1, 2, 3, 4, 5])

In [42]:
y[:, 1]

array([2, 7])

In [43]:
y[:, 1:4]

array([[2, 3, 4],
       [7, 8, 9]])

## boolean selection

In [44]:
x

array([1, 2, 3, 4, 5])

In [45]:
x < 2

array([ True, False, False, False, False], dtype=bool)

In [46]:
x < 2 or x > 4

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [47]:
(x < 2) or (x > 4)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [48]:
(x < 2) | (x > 4)    # 突然感觉变成其他语言的了

array([ True, False, False, False,  True], dtype=bool)

In [49]:
mask = x < 3
mask

array([ True,  True, False, False, False], dtype=bool)

In [50]:
x[mask]     # 通过boolean进行选择

array([1, 2])

In [51]:
np.sum(x < 3)

2

In [52]:
y

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [55]:
x == y[0,]

array([ True,  True,  True,  True,  True], dtype=bool)

In [54]:
a1 = np.arange(9).reshape(3, 3)
a2 = np.arange(9, 0, -1).reshape(3, 3)
a1 < a2

array([[ True,  True,  True],
       [ True,  True, False],
       [False, False, False]], dtype=bool)

## slice

start:end:step

In [56]:
x = np.arange(0, 10)
x[3: 9]

array([3, 4, 5, 6, 7, 8])

In [57]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
x[::2]

array([0, 2, 4, 6, 8])

In [59]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [61]:
x[:6]

array([0, 1, 2, 3, 4, 5])

In [62]:
x[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
y = np.arange(0, 16).reshape(4, 4)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [64]:
y[:, 1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [65]:
y[1:3, 2:4]

array([[ 6,  7],
       [10, 11]])

In [67]:
y[[1, 3], :]    # 选择了指定的（离散的值）

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15]])

## reshape

In [3]:
x = np.arange(0, 9)
y = x.reshape(3, 3)
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
y.reshape(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
y      # 注意这个地方y并没有变

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
y.ravel()     # 将数组进行了展开

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
# 这个例子演示了无论shape如何变，但是数据实际上是指向相同的存储空间！
reshaped = y.reshape(np.size(y))
raveled = y.ravel()

reshaped[2] = 1000
raveled[5] = 2000
y

array([[   0,    1, 1000],
       [   3,    4, 2000],
       [   6,    7,    8]])

In [6]:
reshaped

array([   0,    1, 1000,    3,    4, 2000,    6,    7,    8])

In [9]:
# raveled和flattened没有必要刻意去区分，差别不大。
y = np.arange(0, 9).reshape(3, 3)
flattened = y.flatten()

flattened[0] = 1000
flattened

array([1000,    1,    2,    3,    4,    5,    6,    7,    8])

In [10]:
flattened.shape = (3, 3)     # 通过给shape赋值来进行修改
flattened

array([[1000,    1,    2],
       [   3,    4,    5],
       [   6,    7,    8]])

In [11]:
flattened.T              # 转换

array([[1000,    3,    6],
       [   1,    4,    7],
       [   2,    5,    8]])

## 合并

In [12]:
a = np.arange(9).reshape(3, 3)
b = (a + 1) * 10
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [14]:
# 用hstack进行组合(水平方向)
np.hstack((a, b))

array([[ 0,  1,  2, 10, 20, 30],
       [ 3,  4,  5, 40, 50, 60],
       [ 6,  7,  8, 70, 80, 90]])

In [15]:
# 用vstack进行组合（垂直方向）
np.vstack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [16]:
# 用concatenate进行组合
np.concatenate((a, b), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [17]:
np.concatenate((a, b), axis=1)

array([[ 0,  1,  2, 10, 20, 30],
       [ 3,  4,  5, 40, 50, 60],
       [ 6,  7,  8, 70, 80, 90]])

In [18]:
# 同dstack进行深度组合 
np.dstack((a, b))

array([[[ 0, 10],
        [ 1, 20],
        [ 2, 30]],

       [[ 3, 40],
        [ 4, 50],
        [ 5, 60]],

       [[ 6, 70],
        [ 7, 80],
        [ 8, 90]]])

In [21]:
 # 用column_stack进行组合(和dstack的效果相同)
one_d_a = np.arange(5)
one_d_b = (one_d_a + 1) * 10
np.column_stack((one_d_a, one_d_b))

array([[ 0, 10],
       [ 1, 20],
       [ 2, 30],
       [ 3, 40],
       [ 4, 50]])

In [22]:
# 用row_stack进行组合
np.row_stack((one_d_a, one_d_b))

array([[ 0,  1,  2,  3,  4],
       [10, 20, 30, 40, 50]])

## matrix
* 加
* 减
* 乘
* 内积
* 外积

## 算术运算
* +
* -
* *
* /
+ **
* %

In [23]:
x = np.array([1, 5, 2])
y = np.array([7, 4, 1])
x + y

array([8, 9, 3])

In [24]:
x * y

array([ 7, 20,  2])

In [25]:
x - y

array([-6,  1,  1])

In [26]:
x / y

array([ 0.14285714,  1.25      ,  2.        ])

In [27]:
x % y

array([1, 1, 0])

## 向量的点乘

In [28]:
x = np.array([1, 2, 3])
y = np.array([-7, 8, 9])
np.dot(x, y)

36

In [29]:
dot = np.dot(x, y)
x_modulus = np.sqrt((x*x).sum())
y_modulus = np.sqrt((y*y).sum())
cos_angle = dot / x_modulus / y_modulus # cosine of angle between x and y
angle = np.arccos(cos_angle)
print("angle=",angle)
print(angle * 360 / 2 / np.pi) # angle in degrees
x_modulus*y_modulus*cos_angle

angle= 0.808233789011
46.3083849702


36.0

## matrix

In [32]:
x = np.array(((2, 3), (3, 5)))
y = np.array(((1, 2), (5, -1)))
print(x)
print(y)
print(x * y)
print("-" * 30)
x = np.matrix(((2, 3), (3, 5)))
y = np.matrix(((1, 2), (5, -1)))
print(x * y)

[[2 3]
 [3 5]]
[[ 1  2]
 [ 5 -1]]
[[ 2  6]
 [15 -5]]
------------------------------
[[17  1]
 [28  1]]


In [33]:
x = np.array(((2, 3), (3, 5)))
y = np.matrix(((1, 2), (5, -1)))
np.dot(x, y)

matrix([[17,  1],
        [28,  1]])

In [34]:
np.mat(x) * np.mat(y)

matrix([[17,  1],
        [28,  1]])

假设有有4人,Tom,Mike,Jason,Jack买了三种食品

Tom: 100g A,175g B 210g C

Mike: 90g A, 160g B ,150g C

Jason:200g A, 50g B,100g C

Jack:120g A,310g C

A 2.98/100g

B 3.90/100g

C 1.99/100g

In [37]:
NumPersons = np.array([[100, 175, 210], [90, 160, 150], [200, 50, 100], [120, 0, 310]])
Price_pre_100_g = np.array([2.98, 3.90, 1.99])
Price_in_Cent = np.dot(NumPersons, Price_pre_100_g)
Price_in_Euro = Price_in_Cent/np.array([100, 100, 100, 100])
Price_in_Euro

array([ 13.984,  11.907,   9.9  ,   9.745])

In [38]:
x = np.array([0, 0, 1])
y = np.array([0, 1, 0])
np.cross(x, y)

array([-1,  0,  0])

In [39]:
np.cross(y, x)

array([1, 0, 0])

# 通用函数

In [40]:
m = np.arange(10, 19).reshape(3, 3)

m = np.arange(10, 19).reshape(3, 3)
print (m)
print ("{0} min of the entire matrix".format(m.min()))     # 最小的值
print ("{0} max of entire matrix".format(m.max()))         # 最大的值
print ("{0} position of the min value".format(m.argmin())) # 最小值的位置
print ("{0} position of the max value".format(m.argmax())) # 最大值的位置
print ("{0} mins down each column".format(m.min(axis = 0))) # 每列的最小值
print ("{0} mins across each row".format(m.min(axis = 1)))  # 每行的最小值
print ("{0} maxs down each column".format(m.max(axis = 0))) # 每列的最大值
print ("{0} maxs across each row".format(m.max(axis = 1)))  # 每行的最大值

[[10 11 12]
 [13 14 15]
 [16 17 18]]
10 min of the entire matrix
18 max of entire matrix
0 position of the min value
8 position of the max value
[10 11 12] mins down each column
[10 13 16] mins across each row
[16 17 18] maxs down each column
[12 15 18] maxs across each row


In [41]:
a = np.arange(1, 10)
a.mean(), a.std(), a.var()    # 分别四均值， 标准差， 方差

(5.0, 2.5819888974716112, 6.666666666666667)

In [43]:
a.sum(), a.prod()      # 分别表示和与积

(45, 362880)

In [44]:
a.cumsum(), a.cumprod()     # 分别表示累和和累积

(array([ 1,  3,  6, 10, 15, 21, 28, 36, 45]),
 array([     1,      2,      6,     24,    120,    720,   5040,  40320,
        362880]))

In [45]:
a = np.arange(10)
(a < 5).any()     # 也可以用all()

True

In [46]:
a < 5

array([ True,  True,  True,  True,  True, False, False, False, False, False], dtype=bool)

* 创建array:arange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity, linspace, logspace, mgrid, ogrid, ones, ones_like, r , zeros, zeros_like
* 操作:array split, column stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, item, newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack
* all, any, nonzero, where
* argmax, argmin, argsort, max, min, ptp, searchsorted, sort
* choose, compress, cumprod, cumsum, inner, fill, imag, prod, put, putmask, real, sum
* 基本统计:cov, mean, std, var
* 基本线性代数:cross, dot, outer, svd, vdot