In [1]:
import numpy as np

In [2]:
def squares(values):
    result = []
    for v in values:
        result.append(v * v)
    return result
to_square = range(10000)
%timeit squares(to_square)

1.42 ms ± 33.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [2]:
array_to_square = np.arange(0, 10000)
%timeit array_to_square ** 2

5.8 µs ± 120 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## numpy核心功能ndarray

ndarray的基础
* ndarray.ndim 数组轴的个数，在Python的世界中，轴的个数被称为秩；
* ndarray.shape 数组的维度；
* ndarray.size 数组中元素的个数；
* ndarray.dtype 一个用来描述数组中元素类型的对象；
* ndarray.itemsize 数组中每个元素的字节大小
* ndarray.data 包含实际数组的缓存区，我们实际不需要这个。

In [3]:
x = np.array([1, 2, 3, 4, 5])
x

array([1, 2, 3, 4, 5])

In [4]:
type(x)

numpy.ndarray

In [5]:
x.ndim

1

In [7]:
x.shape

(5,)

In [8]:
x.size

5

In [9]:
x.itemsize

8

In [10]:
x.data

In [12]:
y = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
y

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [13]:
y.ndim

2

In [14]:
y.shape

(2, 5)

In [15]:
y.size

10

In [16]:
y.itemsize

8

In [17]:
y.data

In [18]:
x1 = np.array([1, 2, 3, 4.0, 5.0])
x1.dtype, x.dtype

(dtype('float64'), dtype('int64'))

create ndarray

In [19]:
x2 = np.array([1] * 5)
x2

array([1, 1, 1, 1, 1])

In [20]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [21]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.array(range(0, 10, 2))

array([0, 2, 4, 6, 8])

In [23]:
np.array(range(10, 0, -1))

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [24]:
np.linspace(0, 10, 5)      # 线性的方式创建

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [25]:
np.linspace?

In [27]:
# 向量化操作
print(x)
print(x1)
x + x1

[1 2 3 4 5]
[ 1.  2.  3.  4.  5.]


array([  2.,   4.,   6.,   8.,  10.])

In [28]:
# 生成多维数组，进行链式调用
x2 = np.arange(0, 12).reshape(4, 3)
x2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
np.size(x2)

12

In [30]:
np.size(x2, 0)

4

In [31]:
np.size(x2, 1)

3

In [32]:
np.zeros((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [33]:
np.ones((2, 3, 4), dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [34]:
np.empty((5, 6))     # 生成的值实际上是没有意义的

array([[  0.00000000e+000,   3.10503637e+231,   2.17461181e-314,
          2.18965409e-314,   2.18965566e-314,   2.18810018e-314],
       [  2.17471935e-314,   2.17463932e-314,   2.18639059e-314,
          2.18809986e-314,   2.18639130e-314,   2.18665470e-314],
       [  0.00000000e+000,   0.00000000e+000,   2.18662445e-314,
          2.18809979e-314,   2.18972361e-314,   2.17471910e-314],
       [  2.18648432e-314,   2.18809979e-314,   2.18972361e-314,
          2.17471910e-314,   2.18648432e-314,   2.18665317e-314],
       [  2.19022719e-314,   2.18632178e-314,   2.18665395e-314,
          2.18965438e-314,  -1.28822983e-231,   2.08600688e-308]])

In [35]:
np.random.randint(0, 10, 3)    #生成随机整数

array([9, 0, 4])

In [36]:
np.random.random(10)      # 生成随机数

array([ 0.18120502,  0.84757688,  0.05432345,  0.43468528,  0.73470585,
        0.62599592,  0.73159521,  0.71922365,  0.90469856,  0.81241894])

## 选择数组中的元素